
# Variables
$terminal = kitty
$menu = wofi --show drun
$mainMod = ALT
$secondMod = CTRL

# Autostart
exec-once = quickshell

# Retina screen
monitor=eDP-1,3024x1890@120,auto,1.5

# Keyboard plssss
input {
	kb_layout = fr
	kb_variant = mac
	# kb_options = ctrl:swap_lwin_lctl

	touchpad {
		natural_scroll = true
		clickfinger_behavior = true
		tap-to-click = false
        	tap_button_map = lr-
        	natural_scroll = true
		scroll_factor = 0.2
	}
}

# lil esthetic tweaks
general {
	gaps_in = 4
	gaps_out = 0
	border_size = 2
	col.active_border = rgba(888888aa)
	col.active_border = rgba(333333aa)
	layout = dwindle
}

decoration {
	rounding = 8
	blur {
		enabled = true
		size = 4
		passes = 2
	}
}

animations {
	enabled = true
	bezier = myBezier, 0.05, 0.9, 0.1, 1.05
	animation = windows, 1, 4, myBezier
	animation = windowsOut, 1, 4, default, popin 80%
	animation = border, 1, 5, default
	animation = fade, 1, 4, default
	animation = workspaces, 1, 3, default
}










 ##########################
 #                        #
 #  Keyboard adjustments  #
 #                        #
 ##########################

# Keyboard shortcuts
bind = $secondMod, Return, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod, M, exit
bind = SUPER, Space, exec, $menu
bind = $mainMod, V, togglefloating,
bind = $secondMod, F, fullscreen
bind = $mainMod CTRL, F, fullscreen,

## Moving focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, J, movefocus, u
bind = $mainMod, K, movefocus, d

## Workspaces
bind = $mainMod, code:10, workspace, 1
bind = $mainMod, code:11, workspace, 2
bind = $mainMod, code:12, workspace, 3
bind = $mainMod, code:13, workspace, 4

## Move to Workspaces
bind = $mainMod SHIFT, code:10, movetoworkspace, 1
bind = $mainMod SHIFT, code:11, movetoworkspace, 2
bind = $mainMod SHIFT, code:12, movetoworkspace, 3
bind = $mainMod SHIFT, code:13, movetoworkspace, 4

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
binde = $mainMod, A, sendshortcut, CTRL, A,
binde = $mainMod SHIFT, Z, sendshortcut, CTRL, Y,

binde = SUPER, A, sendshortcut, CTRL, A,
binde = SUPER, C, sendshortcut, CTRL, C, activewindow, ^(?!kitty).*$
binde = SUPER, V, sendshortcut, CTRL, V, activewindow, ^(?!kitty).*$
## Swap Cmd & Ctrl for standard shortcuts
binde = $mainMod, A, sendshortcut, CTRL, A,
binde = $mainMod, B, sendshortcut, CTRL, B,
binde = $mainMod, D, sendshortcut, CTRL, D,
binde = $mainMod, E, sendshortcut, CTRL, E,
binde = $mainMod, F, sendshortcut, CTRL, F,
binde = $mainMod, G, sendshortcut, CTRL, G,
binde = $mainMod, H, sendshortcut, CTRL, H,
binde = $mainMod, I, sendshortcut, CTRL, I,
binde = $mainMod, J, sendshortcut, CTRL, J,
binde = $mainMod, K, sendshortcut, CTRL, K,
binde = $mainMod, L, sendshortcut, CTRL, L,
binde = $mainMod, M, sendshortcut, CTRL, M,
binde = $mainMod, N, sendshortcut, CTRL, N,
binde = $mainMod, O, sendshortcut, CTRL, O,
binde = $mainMod, P, sendshortcut, CTRL, P,
binde = $mainMod, R, sendshortcut, CTRL, R,
binde = $mainMod, S, sendshortcut, CTRL, S,
binde = $mainMod, T, sendshortcut, CTRL, T,
binde = $mainMod, U, sendshortcut, CTRL, U,
binde = $mainMod, W, sendshortcut, CTRL, W,
binde = $mainMod, X, sendshortcut, CTRL, X,
binde = $mainMod, Y, sendshortcut, CTRL, Y,
binde = $mainMod, Z, sendshortcut, CTRL, Z,
